package com.nlp.pro;

public class NLPConstant {
	public static final String[] STOPWORDS = { "without", "see", "unless", "due", "also", "must", "might", "like", "]",
			"[", "}", "{", "<", ">", "?", "\"", "\\", "/", ")", "(", "will", "may", "can", "much", "every", "the", "in",
			"other", "this", "the", "many", "any", "an", "or", "for", "in", "an", "an ", "is", "a", "about", "above",
			"after", "again", "against", "all", "am", "an", "and", "any", "are", "aren’t", "aren't", "as", "at", "be",
			"because", "been", "before", "being", "below", "between", "both", "but", "by", "can’t", "can't", "cannot",
			"could", "couldn’t", "couldn't", "did", "didn’t", "didn't", "do", "does", "doesn’t", "doesn't", "doing",
			"don’t", "don't", "down", "during", "each", "few", "for", "from", "further", "had", "hadn’t", "hadn't",
			"has", "hasn’t", "hasn't", "have", "haven’t", "haven't", "having", "he", "he’d", "he'd", "he’ll", "he'll",
			"he’s", "he's", "her", "here", "here’s", "here's", "hers", "herself", "him", "himself", "his", "how",
			"how’s", "i ", " i", "i'd", "i’d", "i'll", "i’ll", "i'm", "i’m", "i've", "i’ve", "if", "in", "into", "is",
			"isn’t", "isn't", "it", "it's", "it’s", "its", "itself", "let's", "let’s", "me", "more", "most", "mustn’t",
			"mustn't", "my", "myself", "no", "nor", "not", "of", "off", "on", "once", "only", "ought", "our", "ours",
			"ourselves", "out", "over", "own", "same", "shan’t", "she", "she’d", "she'd", "she’ll", "she'll", "she’s",
			"she's", "should", "shouldn’t", "shouldn't", "so", "some", "such", "than", "that", "that’s", "that's",
			"their", "theirs", "them", "themselves", "then", "there", "there’s", "thers's", "these", "they", "they'd",
			"they’d", "they’ll", "they'll", "they’re", "they're", "they’ve", "they've", "this", "those", "through",
			"to", "too", "under", "until", "up", "very", "was", "wasn’t", "wasn't", "we", "we’d", "we'd", "we’ll",
			"we'll", "we’re", "we're", "we’ve", "we've", "were", "weren’t", "weren't", "what", "what’s", "what's",
			"when", "when’s", "when's", "where", "where’s", "where's", "which", "while", "who", "who’s", "who's",
			"whom", "why", "why’s", "why's", "with", "won’t", "won't", "would", "wouldn’t", "wouldn't", "you", "you’d",
			"you'd", "you’ll", "you'll", "you’re", "you're", "you’ve", "you've", "your", "yours", "yourself",
			"yourselves", "Without", "See", "Unless", "Due", "Also", "Must", "Might", "Like", "Will", "May", "Can",
			"Much", "Every", "The", "In", "Other", "This", "The", "Many", "Any", "An", "Or", "For", "In", "An", "An ",
			"Is", "A", "About", "Above", "After", "Again", "Against", "All", "Am", "An", "And", "Any", "Are", "Aren’t",
			"As", "At", "Be", "Because", "Been", "Before", "Being", "Below", "Between", "Both", "But", "By", "Can’t",
			"Cannot", "Could", "Couldn’t", "Did", "Didn’t", "Do", "Does", "Doesn’t", "Doing", "Don’t", "Down", "During",
			"Each", "Few", "For", "From", "Further", "Had", "Hadn’t", "Has", "Hasn’t", "Have", "Haven’t", "Having",
			"He", "He’d", "He’ll", "He’s", "Her", "Here", "Here’s", "Hers", "Herself", "Him", "Himself", "His", "How",
			"How’s", "I ", " I", "I’d", "I’ll", "I’m", "I’ve", "If", "In", "Into", "Is", "Isn’t", "It", "It’s", "Its",
			"Itself", "Let’s", "Me", "More", "Most", "Mustn’t", "My", "Myself", "No", "Nor", "Not", "Of", "Off", "On",
			"Once", "Only", "Ought", "Our", "Ours", "Ourselves", "Out", "Over", "Own", "Same", "Shan’t", "She", "She’d",
			"She’ll", "She’s", "Should", "Shouldn’t", "So", "Some", "Such", "Than", "That", "That’s", "Their", "Theirs",
			"Them", "Themselves", "Then", "There", "There’s", "These", "They", "They’d", "They’ll", "They’re",
			"They’ve", "This", "Those", "Through", "To", "Too", "Under", "Until", "Up", "Very", "Was", "Wasn’t", "We",
			"We’d", "We’ll", "We’re", "We’ve", "Were", "Weren’t", "What", "What’s", "When", "When’s", "Where",
			"Where’s", "Which", "While", "Who", "Who’s", "Whom", "Why", "Why’s", "With", "Won’t", "Would", "Wouldn’t",
			"You", "You’d", "You’ll", "You’re", "You’ve", "Your", "Yours", "Yourself", "Yourselves" };
	public static final String[] COUNTRY_CODE_TWO = { "AD", "AE", "AF", "AG", "AI", "AL", "AM", "AN", "AO", "AR", "AS",
			"AT", "AU", "AW", "AX", "AZ", "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BL", "BM", "BN", "BO",
			"BQ", "BR", "BS", "BT", "BV", "BW", "BY", "BZ", "CA", "CC", "CD", "CF", "CG", "CH", "CI", "CK", "CL", "CM",
			"CN", "CO", "CR", "CU", "CV", "CW", "CX", "CY", "CZ", "DE", "DJ", "DK", "DM", "DO", "DZ", "EC", "EE", "EG",
			"EH", "ER", "ES", "ET", "FI", "FJ", "FK", "FM", "FO", "FR", "GA", "GB", "GD", "GE", "GF", "GG", "GH", "GI",
			"GL", "GM", "GN", "GP", "GQ", "GR", "GS", "GT", "GU", "GW", "GY", "HK", "HM", "HN", "HR", "HT", "HU", "ID",
			"IE", "IL", "IM", "IN", "IO", "IQ", "IR", "IS", "IT", "JE", "JM", "JO", "JP", "KE", "KG", "KH", "KI", "KM",
			"KN", "KP", "KR", "KW", "KY", "KZ", "LA", "LB", "LC", "LI", "LK", "LR", "LS", "LT", "LU", "LV", "LY", "MA",
			"MC", "MD", "ME", "MF", "MG", "MH", "MK", "ML", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV",
			"MW", "MX", "MY", "MZ", "NA", "NC", "NE", "NF", "NG", "NI", "NL", "NO", "NP", "NR", "NU", "NZ", "OM", "PA",
			"PE", "PF", "PG", "PH", "PK", "PL", "PM", "PN", "PR", "PS", "PT", "PW", "PY", "QA", "RE", "RO", "RS", "RU",
			"RW", "SA", "SB", "SC", "SD", "SE", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SR", "SS", "ST",
			"SV", "SX", "SY", "SZ", "TC", "TD", "TF", "TG", "TH", "TJ", "TK", "TL", "TM", "TN", "TO", "TR", "TT", "TV",
			"TW", "TZ", "UA", "UG", "UM", "US", "UY", "UZ", "VA", "VC", "VE", "VG", "VI", "VN", "VU", "WF", "WS", "YE",
			"YT", "ZA", "ZM", "ZW" };
	public static final String[] COUNTRY_CODE_THREE = { "AND", "ARE", "AFG", "ATG", "AIA", "ALB", "ARM", "ANT", "AGO",
			"ARG", "ASM", "AUT", "AUS", "ABW", "ALA", "AZE", "BIH", "BRB", "BGD", "BEL", "BFA", "BGR", "BHR", "BDI",
			"BEN", "BLM", "BMU", "BRN", "BOL", "BES", "BRA", "BHS", "BTN", "BVT", "BWA", "BLR", "BLZ", "CAN", "CCK",
			"COD", "CAF", "COG", "CHE", "CIV", "COK", "CHL", "CMR", "CHN", "COL", "CRI", "CUB", "CPV", "CUW", "CXR",
			"CYP", "CZE", "DEU", "DJI", "DNK", "DMA", "DOM", "DZA", "ECU", "EST", "EGY", "ESH", "ERI", "ESP", "ETH",
			"FIN", "FJI", "FLK", "FSM", "FRO", "FRA", "GAB", "GBR", "GRD", "GEO", "GUF", "GGY", "GHA", "GIB", "GRL",
			"GMB", "GIN", "GLP", "GNQ", "GRC", "SGS", "GTM", "GUM", "GNB", "GUY", "HKG", "HMD", "HND", "HRV", "HTI",
			"HUN", "IDN", "IRL", "ISR", "IMN", "IND", "IOT", "IRQ", "IRN", "ISL", "ITA", "JEY", "JAM", "JOR", "JPN",
			"KEN", "KGZ", "KHM", "KIR", "COM", "KNA", "PRK", "KOR", "KWT", "CYM", "KAZ", "LAO", "LBN", "LCA", "LIE",
			"LKA", "LBR", "LSO", "LTU", "LUX", "LVA", "LBY", "MAR", "MCO", "MDA", "MNE", "MAF", "MDG", "MHL", "MKD",
			"MLI", "MMR", "MNG", "MAC", "MNP", "MTQ", "MRT", "MSR", "MLT", "MUS", "MDV", "MWI", "MEX", "MYS", "MOZ",
			"NAM", "NCL", "NER", "NFK", "NGA", "NIC", "NLD", "NOR", "NPL", "NRU", "NIU", "NZL", "OMN", "PAN", "PER",
			"PYF", "PNG", "PHL", "PAK", "POL", "SPM", "PCN", "PRI", "PSE", "PRT", "PLW", "PRY", "QAT", "REU", "ROU",
			"SRB", "RUS", "RWA", "SAU", "SLB", "SYC", "SDN", "SWE", "SGP", "SHN", "SVN", "SJM", "SVK", "SLE", "SMR",
			"SEN", "SOM", "SUR", "SSD", "STP", "SLV", "SXM", "SYR", "SWZ", "TCA", "TCD", "ATF", "TGO", "THA", "TJK",
			"TKL", "TLS", "TKM", "TUN", "TON", "TUR", "TTO", "TUV", "TWN", "TZA", "UKR", "UGA", "UMI", "USA", "URY",
			"UZB", "VAT", "VCT", "VEN", "VGB", "VIR", "VNM", "VUT", "WLF", "WSM", "YEM", "MYT", "ZAF", "ZMB", "ZWE" };
	public static final String[] COUNTRY_NAME = { "Andorra", "United Arab Emirates", "Afghanistan",
			"Antigua and Barbuda", "Anguilla", "Albania", "Armenia", "Netherlands Antilles", "Angola", "Argentina",
			"American Samoa", "Austria", "Australia", "Aruba", "Åland Islands", "Azerbaijan", "Bosnia and Herzegovina",
			"Barbados", "Bangladesh", "Belgium", "Burkina Faso", "Bulgaria", "Bahrain", "Burundi", "Benin",
			"Saint Barthélemy", "Bermuda", "Brunei", "Bolivia", "Bonaire, Sint Eustatius and Saba", "Brazil", "Bahamas",
			"Bhutan", "Bouvet Island", "Botswana", "Belarus", "Belize", "Canada", "Cocos Islands",
			"The Democratic Republic Of Congo", "Central African Republic", "Congo", "Switzerland", "Côte d'Ivoire",
			"Cook Islands", "Chile", "Cameroon", "China", "Colombia", "Costa Rica", "Cuba", "Cape Verde", "Curaçao",
			"Christmas Island", "Cyprus", "Czech Republic", "Germany", "Djibouti", "Denmark", "Dominica",
			"Dominican Republic", "Algeria", "Ecuador", "Estonia", "Egypt", "Western Sahara", "Eritrea", "Spain",
			"Ethiopia", "Finland", "Fiji", "Falkland Islands", "Micronesia", "Faroe Islands", "France", "Gabon",
			"United Kingdom", "Grenada", "Georgia", "French Guiana", "Guernsey", "Ghana", "Gibraltar", "Greenland",
			"Gambia", "Guinea", "Guadeloupe", "Equatorial Guinea", "Greece",
			"South Georgia And The South Sandwich Islands", "Guatemala", "Guam", "Guinea-Bissau", "Guyana", "Hong Kong",
			"Heard Island And McDonald Islands", "Honduras", "Croatia", "Haiti", "Hungary", "Indonesia", "Ireland",
			"Israel", "Isle Of Man", "India", "British Indian Ocean Territory", "Iraq", "Iran", "Iceland", "Italy",
			"Jersey", "Jamaica", "Jordan", "Japan", "Kenya", "Kyrgyzstan", "Cambodia", "Kiribati", "Comoros",
			"Saint Kitts And Nevis", "North Korea", "South Korea", "Kuwait", "Cayman Islands", "Kazakhstan", "Laos",
			"Lebanon", "Saint Lucia", "Liechtenstein", "Sri Lanka", "Liberia", "Lesotho", "Lithuania", "Luxembourg",
			"Latvia", "Libya", "Morocco", "Monaco", "Moldova", "Montenegro", "Saint Martin", "Madagascar",
			"Marshall Islands", "Macedonia", "Mali", "Myanmar", "Mongolia", "Macao", "Northern Mariana Islands",
			"Martinique", "Mauritania", "Montserrat", "Malta", "Mauritius", "Maldives", "Malawi", "Mexico", "Malaysia",
			"Mozambique", "Namibia", "New Caledonia", "Niger", "Norfolk Island", "Nigeria", "Nicaragua", "Netherlands",
			"Norway", "Nepal", "Nauru", "Niue", "New Zealand", "Oman", "Panama", "Peru", "French Polynesia",
			"Papua New Guinea", "Philippines", "Pakistan", "Poland", "Saint Pierre And Miquelon", "Pitcairn",
			"Puerto Rico", "Palestine", "Portugal", "Palau", "Paraguay", "Qatar", "Reunion", "Romania", "Serbia",
			"Russia", "Rwanda", "Saudi Arabia", "Solomon Islands", "Seychelles", "Sudan", "Sweden", "Singapore",
			"Saint Helena", "Slovenia", "Svalbard And Jan Mayen", "Slovakia", "Sierra Leone", "San Marino", "Senegal",
			"Somalia", "Suriname", "South Sudan", "Sao Tome And Principe", "El Salvador", "Sint Maarten (Dutch part)",
			"Syria", "Swaziland", "Turks And Caicos Islands", "Chad", "French Southern Territories", "Togo", "Thailand",
			"Tajikistan", "Tokelau", "Timor-Leste", "Turkmenistan", "Tunisia", "Tonga", "Turkey", "Trinidad and Tobago",
			"Tuvalu", "Taiwan", "Tanzania", "Ukraine", "Uganda", "United States Minor Outlying Islands",
			"United States", "Uruguay", "Uzbekistan", "Vatican", "Saint Vincent And The Grenadines", "Venezuela",
			"British Virgin Islands", "U.S. Virgin Islands", "Vietnam", "Vanuatu", "Wallis And Futuna", "Samoa",
			"Yemen", "Mayotte", "South Africa", "Zambia", "Zimbabwe" };
	public static final String[] CURRENCY_SYMBOL = { "EUR", "AED", "AFN", "XCD", "ALL", "AMD", "ANG", "AOA", "ARS", "$",
			"AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "XOF", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BRL", "BSD",
			"BTN", "NOK", "BWP", "BYR", "BZD", "CAD", "CDF", "XAF", "CHF", "NZD", "CLP", "CNY", "COP", "CRC", "CUP",
			"CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "MAD", "ERN", "ETB", "FJD", "FKP", "GBP", "GEL", "GHS",
			"GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HRK", "HTG", "HUF", "IDR", "ILS", "INR", "IQD", "IRR",
			"ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP",
			"LKR", "LRD", "LSL", "LTL", "LYD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRO", "MUR", "MVR", "MWK",
			"MXN", "MYR", "MZN", "NAD", "XPF", "NGN", "NIO", "NPR", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN",
			"PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLL", "SOS",
			"SRD", "SSP", "STD", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS",
			"UAH", "UGX", "UYU", "UZS", "VEF", "VND", "VUV", "WST", "YER", "ZAR", "ZMW", "ZWL" };
	public static final String TOKENIZEPARENTDIR = "/test";
	public static final String PARENTDIR = "/nlp";
	public static final String EMAILREGEX = "([\\w-]+(?:\\.[\\w-]+)*)@((?:[\\w-]+\\.)*\\w[\\w-]{0,66})\\.([a-z]{2,6})";
	public static final String IPREGEX = "^([0-9]|[1-9][0-9]|[1][0-9][0-9]|[2][0-5][0-5])[.]([0-9]|[1-9][0-9]|[1][0-9][0-9]|[2][0-5][0-5])[.]([0-9]|[1-9][0-9]|[1][0-9][0-9]|[2][0-5][0-5])[.]([0-9]|[1-9][0-9]|[1][0-9][0-9]|[2][0-5][0-5])$";
	public static final String HOSTNAMEREGEX = "([a-zA-Z0-9]*\\.)?([a-zA-Z0-9]*\\.)([a-z]*)(\\.[a-z]{2,})?";
	public static final String DATEREGEX = "((?=\\d{4})\\d{4}|(?=[a-zA-Z]{3})[a-zA-Z]{3}|\\d{2})((?=\\/)\\/|\\-)((?=[0-9]{2})[0-9]{2}|(?=[0-9]{1,2})[0-9]{1,2}|[a-zA-Z]{3})((?=\\/)\\/|\\-)((?=[0-9]{4})[0-9]{4}|(?=[0-9]{2})[0-9]{2}|[a-zA-Z]{3})";
	public static final String MERIDIEM = "(?:am)?(?:AM)?(?:pm)?(?:PM)?";
	public static final String TIMEREGEX = "([0-9]{1,2})\\:([0-9]{1,2})(\\:[0-9]{1,2})?(?: )?" + MERIDIEM;
	public static final String ACCEPT_CHARACTER = "[^a-zA-Z0-9\\/\\-\\:]";
	public static final String URL = "^(https?:\\/\\/)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([\\/\\w \\.-]*)*\\/?$";
}
